/* GENERATED by stm8/ble/webapp/gen_tables.py from the image sha256
 *   3259eb255899af14b038d50758adb671514b5b003b3352ba037cea1a78e3dbb8
 *
 * DO NOT EDIT -- re-run the generator, which reads the tables out of the firmware image so that a
 * hand-typed copy cannot drift from the device. The host tools read them from the image at runtime
 * for the same reason; a browser cannot, so this happens one step earlier.
 *
 * Bit addresses index segment RAM $540C..$5418 as byte ($540C + bit>>3), bit (bit&7). WHAT THE
 * ICONS MEAN is measured and not derivable from the firmware -- stm8/docs/10_lcd_panel.md is the
 * legend, and index 4 is a table entry for a crosspoint this glass does not implement.
 *
 * GLYPHS and ALIASES are the one thing here that is NOT read out of the image: which character gets
 * which of the font's 42 shapes is a judgement, and its home is stm8/ble/lcd_font.py. They are
 * copied through the same generator so the app cannot hold a stale opinion of what a letter looks
 * like -- the shapes themselves still come from the firmware.
 */

/** [slot 0..3][segment a..g] -> bit address. SLOT 0 IS THE RIGHTMOST CELL. */
export const SEGMAP: number[][] = [[1, 29, 57, 85, 58, 2, 30], [3, 31, 59, 87, 60, 4, 32], [5, 33, 61, 89, 62, 6, 34], [7, 35, 63, 91, 65, 9, 37]]
/** The 14 fixed icons, in `ICONS` order. */
export const SYM_A: number[] = [66, 67, 11, 0, 102, 39, 56, 88, 86, 90, 94, 95, 28, 84]
/** The 24-slot bar across the top, left to right. */
export const SYM_B: number[] = [96, 68, 40, 12, 13, 41, 69, 97, 98, 70, 42, 14, 15, 43, 71, 99, 100, 72, 44, 16, 17, 45, 73, 101]
/** The weekday row, Monday first. */
export const DAYS: number[] = [38, 10, 93, 92, 64, 36, 8]
export const ICONS: string[] = ["suitcase", "moon", "sun", "degree", "(phantom)", "window", "battery", "dp-after-2", "dp-after-3", "colon", "Manu", "Auto", "%", "hour-ticks"]
/** Segment pattern -> the character it draws. An absent pattern is unknown, not blank. */
export const PATCHAR: Record<string, string> = {"6": "1", "7": "7", "28": "u", "56": "L", "57": "C", "63": "0", "64": "-", "79": "3", "80": "r", "84": "n", "88": "c", "91": "2", "92": "o", "94": "d", "102": "4", "109": "5", "110": "y", "111": "9", "113": "F", "115": "P", "118": "H", "119": "A", "120": "t", "121": "E", "124": "b", "125": "6", "127": "8"}

/** A cell that draws nothing. It is also the pad a short message is filled out with. */
export const BLANK = 255
/** How many cells the panel shows at once. More than this scrolls. */
export const CELLS = 4
/** How many glyphs a `cmd 0x0F` frame carries, scrolled or not. */
export const FIELD = 9
/** Character -> glyph index, for WRITING a message. Anything absent cannot be drawn. */
export const GLYPHS: Record<string, number> = {"0": 0, "1": 1, "2": 2, "3": 3, "4": 4, "5": 5, "6": 6, "7": 7, "8": 8, "9": 9, "A": 10, "b": 11, "C": 12, "d": 13, "E": 14, "F": 15, "G": 16, "H": 17, "I": 18, "J": 19, "K": 20, "L": 21, "m": 22, "n": 23, "O": 24, "P": 25, "q": 26, "r": 27, "S": 28, "t": 29, "U": 30, "u": 31, "y": 34, "Z": 35, "W": 32, " ": 255, "-": 36, "_": 255}
/** Letters with no shape of their own, mapped to the case that has one. */
export const ALIASES: Record<string, string> = {"a": "A", "B": "b", "c": "C", "D": "d", "e": "E", "f": "F", "g": "G", "h": "H", "i": "I", "j": "J", "k": "K", "l": "L", "M": "m", "N": "n", "o": "O", "p": "P", "Q": "q", "R": "r", "s": "S", "T": "t", "V": "U", "v": "u", "Y": "y", "Z": "Z", "w": "W", "X": "H", "x": "H", "z": "Z"}
